<?php

namespace Husel\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JournalDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalDetailRepository extends EntityRepository
{
}
